/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasimanajemen;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import aplikasimanajemen.TransactionManager;

/**
 *
 * @author HP
 */
public class MainApp extends JFrame {

    private JTextField txtAkunPengirim;
    private JTextField txtAkunPenerima;
    private JTextField txtJumlahTransfer;
    private JButton btnTransfer;
    private JTextArea txtResult;

    public MainApp() {
        setTitle("Manajemen Transaksi - Transfer Saldo");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        JPanel panel = new JPanel();
        panel.setLayout(null);

        JLabel lblAkunPengirim = new JLabel("Akun Pengirim (ID):");
        lblAkunPengirim.setBounds(20, 20, 150, 25);
        panel.add(lblAkunPengirim);
        txtAkunPengirim = new JTextField();
        txtAkunPengirim.setBounds(180, 20, 150, 25);
        panel.add(txtAkunPengirim);
        JLabel lblAkunPenerima = new JLabel("Akun Penerima (ID):");
        lblAkunPenerima.setBounds(20, 60, 150, 25);
        panel.add(lblAkunPenerima);
        txtAkunPenerima = new JTextField();
        txtAkunPenerima.setBounds(180, 60, 150, 25);
        panel.add(txtAkunPenerima);
        JLabel lblJumlahTransfer = new JLabel("Jumlah Transfer:");
        lblJumlahTransfer.setBounds(20, 100, 150, 25);
        panel.add(lblJumlahTransfer);
        txtJumlahTransfer = new JTextField();
        txtJumlahTransfer.setBounds(180, 100, 150, 25);
        panel.add(txtJumlahTransfer);
        btnTransfer = new JButton("Transfer");
        btnTransfer.setBounds(130, 150, 100, 30);
        panel.add(btnTransfer);
        txtResult = new JTextArea();
        txtResult.setBounds(20, 190, 350, 50);
        txtResult.setEditable(false);
        panel.add(txtResult);
        add(panel);

        // Action Listener untuk button Transfer
        btnTransfer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               
                int pengirim = Integer.parseInt(txtAkunPengirim.getText());
                int penerima = Integer.parseInt(txtAkunPenerima.getText());
                double jumlah = Double.parseDouble(txtJumlahTransfer.getText());
                try {
                    TransactionManager.transferSaldo(pengirim, penerima, jumlah);
                    txtResult.setText("Transfer berhasil.");
                } catch (Exception ex) {
                    txtResult.setText("Error: " + ex.getMessage());
                }
            }
        });
    }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
